language: csharp
mono: none
matrix:
  include:
    - name: "Linux Qt 5.12.0"
      dotnet: 3.1
      os: linux
      dist: xenial
    - name: "OSX Qt 5.12.0"
      dotnet: 3.1.300
      os: osx
      osx_image: xcode9.4
if: tag IS blank
git:
  depth: false
before_install:
  # to support running tests for .NET Core 2.1 LTS, install the runtime side-by-side
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install dotnet-runtime-2.1 ; fi
  # Copied from csharp.rb in the travis-build repo
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget --retry-connrefused --waitretry=1 -O /tmp/dotnet.pkg https://download.visualstudio.microsoft.com/download/pr/bc303f50-ec1d-43b4-b846-51d5fc3c1a2d/4f0abfa496fba6a387dc80b450eb65b8/dotnet-runtime-2.1.18-osx-x64.pkg; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo installer -package "/tmp/dotnet.pkg" -target "/" -verboseR; fi

script:
  - ./build/travis.sh