image: Visual Studio 2017
install:
  - choco install gitversion.portable -pre -y --version 4.0.0
before_build:
  - cmd: rm -r C:\Tools\GitVersion\
  - cmd: gitversion > version.json
  - cmd: git submodule update --init
build_script:
  - cmd: build/appveyor.bat
after_build:
  - ps: Get-ChildItem output\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
